### ISSUE TITLE
Omega tries to read `NTracers` from input file

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/Omega#173]
When I try to read in an `InitialState` stream with the following spec in the `omega.yml` file:
``` yaml
    InitialState:
      UsePointerFile: false
      Filename: init.nc
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: OnStartup
      UseStartEnd: false
      Contents:
      - State
      - Base
```
I'm seeing:
```
[* error] [IO.cpp:334] PIO error while reading dimension NTracers 
[* error] [IO.cpp:334] PIO error while reading dimension nTracers 
[* warning] [IOStream.cpp:668] Dimension NTracers not found in input stream InitialState
```
I don't think we will ever expect to have `NTracres` (or `nTracers`) as a dimension in a file, right?  It is a convenience in code but I don't think we have a capability to write out the tracer array with this dimension.  At the very least, we should skip over this dimension without a warning let alone an error if it doesn't exist.
