### ISSUE TITLE
Error when `FreqUnits` set to `never` in `InitialState` stream

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/Omega#181]
I am trying to do a restart run.  When I have:
```yaml
    InitialState:
      UsePointerFile: false
      Filename: init.nc
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: never
      UseStartEnd: false
      Contents:
      - State
      - Tracers
```
I am seeing:
```
$ cat omega.log

[* info] [TimeMgr.cpp:1218] Omega using calendar type: No Leap
[* warning] [IOStream.cpp:527] Stream InitialState has IO frequency of never and will be skipped
[* info] [Tracers.cpp:46] Tracers::init() called
[* error] [IOStream.cpp:252] Unable to read stream InitialState. Stream not defined
[* critical] [OceanInit.cpp:182] Error reading the initial state file
[* critical] [OceanInit.cpp:56] ocnInit: Error initializing Omega modules
[* error] [OceanDriver.cpp:32] Error initializing OMEGA
[* info] [Tracers.cpp:249] Tracers::clear() called
[* error] [OceanDriver.cpp:61] OMEGA terminating due to error

```

**Comment by xylar** [comment]
This is on Chrysalis (with Intel).  My directory is:
```
/lcrc/group/e3sm/ac.xylar/polaris_0.5/chrysalis/test_20241205/omega_cosine_bell_restart/ocean/spherical/icos/cosine_bell/restart/restart_run
```
I'm using the latest `develop`.

My full YAML is:
``` yaml
Omega:
  TimeIntegration:
    CalendarType: No Leap
    TimeStepper: RungeKutta4
    TimeStep: 0000_00:24:00.000
    StartTime: 0001-01-01_00:24:00
    StopTime: none
    RunDuration: 0000_00:24:00.000
  Dimension:
    NVertLevels: 1
  Decomp:
    HaloWidth: 3
    DecompMethod: MetisKWay
  State:
    NTimeLevels: 2
  Advection:
    FluxThicknessType: Center
    FluxTracerType: Center
  Tendencies:
    ThicknessFluxTendencyEnable: false
    PVTendencyEnable: false
    KETendencyEnable: false
    SSHTendencyEnable: false
    VelDiffTendencyEnable: false
    ViscDel2: 1.0e3
    VelHyperDiffTendencyEnable: false
    ViscDel4: 1.2e11
    TracerHorzAdvTendencyEnable: true
    TracerDiffTendencyEnable: false
    EddyDiff2: 10.0
    TracerHyperDiffTendencyEnable: false
    EddyDiff4: 0.0
  Tracers:
    Base: [Temperature, Salinity]
    Debug: [Debug1, Debug2, Debug3]
  IOStreams:
    # InitialState should only be used when starting from scratch
    # After the simulations initial start, the frequency should be
    # changed to never so that the initial state file is not read.
    InitialState:
      UsePointerFile: false
      Filename: init.nc
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: never
      UseStartEnd: false
      Contents:
      - State
      - Tracers
    RestartRead:
      UsePointerFile: false
      PointerFilename: ocn.pointer
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: OnStartup
      UseStartEnd: true
      StartTime: 0001-01-01_00:24:00
      EndTime: 99999-12-31_00:00:00
      Contents:
      - Restart
      Filename: ../restarts/rst.$Y-$M-$D_$h.$m.$s
    RestartWrite:
      UsePointerFile: false
      PointerFilename: ocn.pointer
      Filename: ../restarts/rst.$Y-$M-$D_$h.$m.$s
      Mode: write
      IfExists: replace
      Precision: double
      Freq: 1
      FreqUnits: seconds
      UseStartEnd: false
      Contents:
      - Restart
    History:
      UsePointerFile: false
      Filename: output.nc
      Mode: write
      IfExists: replace
      Precision: double
      Freq: 1440
      FreqUnits: seconds
      UseStartEnd: false
      Contents:
      - Tracers
      - LayerThickness
      - NormalVelocity
```
